---
scenario:
  # Because we need to unregister our hosts with RHSM using the cleanup playbook we have to deviate from the default
  # test sequence provided by molecule, more details here: https://molecule.readthedocs.io/en/latest/configuration.html#scenario
  test_sequence:
    - lint
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy

dependency:
  name: galaxy
  options:
    # These paths are relative to where molecule is being executed from
    role-file: "roles/requirements.yml"
    requirements-file: "collections/requirements.yml"

driver:
  # You can override the driver by setting CONTAINER_RT to a different driver, realistically either docker|podman
  name: ${CONTAINER_RT:-podman}

platforms:
  - name: ${MOLECULE_DISTRO:-"rhel8"}
    image: ${MOLECULE_IMAGE:-"registry.access.redhat.com/ubi8/ubi-init"}
    command: ${MOLECULE_COMMAND:-"/usr/sbin/init"}
    # Privileged and volume mounts are not needed in podman due to systemd auto detection
    # but are kept here for compatability with docker (man podman run).
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
