---
- name: Cleanup
  hosts: all
  gather_facts: true
  tasks:

    - name: 'Unregister Container with RHSM if running in Docker'
      community.general.redhat_subscription:
        state: absent
      when: ansible_distribution == "RedHat" and lookup('env', 'CONTAINER_RT') == "docker"
